import { test, expect, describe } from "bun:test";
import { mkdtempSync, writeFileSync, readFileSync, chmodSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { SESSION_DIED_STATUS_PREFIX } from "../shared/types.ts";

// Pre-set AGETOR_DATA_DIR before claude-tmux.ts's transitive db.ts import —
// mirrors claude-tmux-unknown-command.test.ts / claude-tmux-queue.test.ts. A
// static import would be hoisted above this assignment and capture the
// wrong data dir (db.ts reads the env var at module load).
process.env.AGETOR_DATA_DIR = mkdtempSync(path.join(tmpdir(), "agetor-tmux-local-cmd-"));

const {
  __forTest,
  dismissTmuxPrompt,
  sendSlashCommand,
  CLAUDE_UNKNOWN_COMMAND_STATUS_PREFIX,
  CLAUDE_API_ERROR_STATUS_PREFIX,
} = await import("./claude-tmux.ts");

const {
  isLocalCommandStdoutEvent,
  localCommandNameOf,
  dispatchLine,
  flush,
  signalIdleSettle,
  IDLE_SETTLE_STATUS_TEXT,
  SLASH_CONFIRM_POLL_MS,
} = __forTest;

/* ────────────────────────────────────────────────────────────────────────── *
 * Shared test scaffolding — mirrors claude-tmux-unknown-command.test.ts /
 * claude-tmux-queue.test.ts.
 * ────────────────────────────────────────────────────────────────────────── */

interface Recorded { stream: string; data: string }
function recorder() {
  const out: Recorded[] = [];
  return {
    out,
    onChunk: (stream: string, data: string) => out.push({ stream, data }),
  };
}

function freshSession(): { taskId: string; jsonlPath: string; state: ReturnType<typeof __forTest.installSession> } {
  const dir = mkdtempSync(path.join(tmpdir(), "agetor-local-cmd-"));
  const jsonlPath = path.join(dir, `${randomUUID()}.jsonl`);
  writeFileSync(jsonlPath, "");
  const taskId = randomUUID();
  const state = __forTest.installSession(taskId, jsonlPath);
  return { taskId, jsonlPath, state };
}

/** Verbatim claude 2.1.245 JSONL shapes from the plan (docs/plans/
 *  model-effort-local-command-turns.md §2), built via JSON.stringify (not
 *  hand-typed strings) per the task's instruction. */
const caveatLine = JSON.stringify({
  type: "user",
  isMeta: true,
  uuid: "c1",
  message: {
    role: "user",
    content:
      "<local-command-caveat>Caveat: The messages below were generated by the user while " +
      "running local commands. DO NOT respond to these messages or otherwise consider them " +
      "in your response unless the user explicitly asks you to.</local-command-caveat>",
  },
});

const commandNameLine = JSON.stringify({
  type: "user",
  uuid: "c2",
  message: {
    role: "user",
    content:
      "<command-name>/effort</command-name>\n            <command-message>effort</command-message>\n" +
      "            <command-args>high</command-args>",
  },
});

const stdoutLine = JSON.stringify({
  type: "user",
  uuid: "c3",
  message: {
    role: "user",
    content:
      "<local-command-stdout>Set effort level to high (saved as your default for new sessions): " +
      "Comprehensive implementation with extensive testing and documentation</local-command-stdout>",
  },
});

const freshSessionCommandNameLine = JSON.stringify({
  type: "system",
  subtype: "local_command",
  uuid: "s1",
  content: "<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>",
  level: "info",
});

const freshSessionStdoutLine = JSON.stringify({
  type: "system",
  subtype: "local_command",
  uuid: "s2",
  content: "<local-command-stdout>Kept model as Opus 4.8</local-command-stdout>",
  level: "info",
});

/**
 * Recording variant of a fake tmux bin — copied from
 * claude-tmux-queue.test.ts (not exported from that file, so duplicated
 * here). Writes a small bun script as the tmux bin that appends one
 * `{ ns, argv }` JSON line per invocation to a log file, so tests can assert
 * both the order and content of tmux calls without a real tmux server.
 */
function withRecordingTmuxBin<T>(fn: (logPath: string) => Promise<T>): Promise<T> {
  const dir = mkdtempSync(path.join(tmpdir(), "agetor-tmux-rec-"));
  const binPath = path.join(dir, "tmux");
  const logPath = path.join(dir, "log.jsonl");
  writeFileSync(
    binPath,
    `#!${process.execPath}\n` +
      `import { appendFileSync } from "node:fs";\n` +
      `appendFileSync(${JSON.stringify(logPath)}, JSON.stringify({ ms: Date.now(), argv: process.argv.slice(2) }) + "\\n");\n`,
  );
  chmodSync(binPath, 0o755);
  const prevBin = process.env.AGETOR_TMUX_BIN;
  process.env.AGETOR_TMUX_BIN = binPath;
  return fn(logPath).finally(() => {
    if (prevBin === undefined) delete process.env.AGETOR_TMUX_BIN;
    else process.env.AGETOR_TMUX_BIN = prevBin;
  });
}

function readTmuxLog(logPath: string): Array<{ ms: number; argv: string[] }> {
  let raw: string;
  try {
    raw = readFileSync(logPath, "utf8");
  } catch {
    return [];
  }
  return raw.split("\n").filter(Boolean).map((l) => JSON.parse(l)).map((entry) => {
    // Every tmux spawn leads with tmuxSocketArgs() (["-L", <name>]) under
    // `bun test` — strip that pair so send-keys assertions here don't have
    // to know about socket isolation. Mirrors claude-tmux-queue.test.ts.
    const [a, , ...rest] = entry.argv;
    return a === "-L" ? { ...entry, argv: rest } : entry;
  });
}

/* ────────────────────────────────────────────────────────────────────────── *
 * isLocalCommandStdoutEvent — truth table
 * ────────────────────────────────────────────────────────────────────────── */

describe("isLocalCommandStdoutEvent — truth table", () => {
  test("user, non-meta, <local-command-stdout> string content → true", () => {
    expect(isLocalCommandStdoutEvent({
      type: "user",
      // AssistantMessage & UserMessage's intersected `content` type can't
      // structurally admit a bare string literal (a real TS quirk of that
      // production intersection, not something this test file can fix) —
      // cast at the call site so this synthetic JSONL-shaped fixture still
      // exercises the real function.
      message: { content: "<local-command-stdout>Set effort level to high</local-command-stdout>" },
    } as any)).toBe(true);
  });

  test("system/local_command with <local-command-stdout> in content → true", () => {
    expect(isLocalCommandStdoutEvent({
      type: "system",
      subtype: "local_command",
      content: "<local-command-stdout>Kept model as Opus 4.8</local-command-stdout>",
    })).toBe(true);
  });

  test("isMeta <local-command-caveat> breadcrumb → false (claude's note-to-self, not the result)", () => {
    expect(isLocalCommandStdoutEvent({
      type: "user",
      isMeta: true,
      message: { content: "<local-command-caveat>Caveat: ...</local-command-caveat>" },
    } as any)).toBe(false);
  });

  test("user <command-name> line → false", () => {
    expect(isLocalCommandStdoutEvent({
      type: "user",
      message: {
        content: "<command-name>/effort</command-name>\n<command-message>effort</command-message>\n<command-args>high</command-args>",
      },
    } as any)).toBe(false);
  });

  test("system/local_command <command-name> line → false", () => {
    expect(isLocalCommandStdoutEvent({
      type: "system",
      subtype: "local_command",
      content: "<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>",
    })).toBe(false);
  });

  test("assistant line → false", () => {
    expect(isLocalCommandStdoutEvent({
      type: "assistant",
      message: {
        content: [{ type: "text", text: "<local-command-stdout>should never appear on an assistant line</local-command-stdout>" }],
      },
    })).toBe(false);
  });

  test("user tool_result array content → false", () => {
    expect(isLocalCommandStdoutEvent({
      type: "user",
      message: { content: [{ type: "tool_result", tool_use_id: "t1", content: "ok", is_error: false }] },
    })).toBe(false);
  });
});

/* ────────────────────────────────────────────────────────────────────────── *
 * localCommandNameOf — truth table (F1: the identity half of the
 * local-command settle gate)
 * ────────────────────────────────────────────────────────────────────────── */

describe("localCommandNameOf — truth table", () => {
  test("user <command-name> line → the command token", () => {
    expect(localCommandNameOf(JSON.parse(commandNameLine))).toBe("/effort");
  });

  test("system/local_command <command-name> line → the command token", () => {
    expect(localCommandNameOf(JSON.parse(freshSessionCommandNameLine))).toBe("/model");
  });

  test("user <local-command-stdout> line → null", () => {
    expect(localCommandNameOf(JSON.parse(stdoutLine))).toBeNull();
  });

  test("system/local_command <local-command-stdout> line → null", () => {
    expect(localCommandNameOf(JSON.parse(freshSessionStdoutLine))).toBeNull();
  });

  test("isMeta <local-command-caveat> breadcrumb → null", () => {
    expect(localCommandNameOf(JSON.parse(caveatLine))).toBeNull();
  });

  test("assistant line → null", () => {
    expect(localCommandNameOf({
      type: "assistant",
      message: {
        content: [{ type: "text", text: "<command-name>/effort</command-name>" }],
      },
    })).toBeNull();
  });
});

/* ────────────────────────────────────────────────────────────────────────── *
 * Local-command turn settle — dispatchLine's slot.slashCommand gate
 * ────────────────────────────────────────────────────────────────────────── */

test("slash slot: caveat is silent, command-name + stdout emit 'user' chunks, and stdout stages a bannerless pending that idle-fires the slot", async () => {
  const { taskId, state } = freshSession();
  try {
    // Sanity: this fixture's command-name token really is "/effort" — the
    // slot below is pushed with `slashCommand: "/effort"` specifically so it
    // matches, and a drifted fixture would silently defeat that.
    expect(localCommandNameOf(JSON.parse(commandNameLine))).toBe("/effort");

    const rec = recorder();
    const done = new Promise<number>((resolve, reject) => {
      state.turnQueue.push({ onChunk: rec.onChunk, resolve, reject, slashCommand: "/effort" });
    });

    dispatchLine(state, caveatLine);
    // The caveat is claude's note-to-self — silenced entirely, no chunk at all.
    expect(rec.out.length).toBe(0);
    expect(state.lastLocalCommandName).toBeNull();

    dispatchLine(state, commandNameLine);
    expect(rec.out.some((c) => c.stream === "user" && c.data.includes("<command-name>/effort</command-name>"))).toBe(true);
    // The command-name line is what arms the identity gate.
    expect(state.lastLocalCommandName).toBe("/effort");

    dispatchLine(state, stdoutLine);
    expect(rec.out.some((c) => c.stream === "user" && c.data.includes("<local-command-stdout>Set effort level to high"))).toBe(true);

    // Not yet popped: the stdout line staged a bannerless pending end_turn,
    // but the slot itself waits for the next line or the idle-fire.
    expect(state.pendingEndTurn).not.toBeNull();
    expect(state.pendingEndTurn!.emitBanner).toBe(false);
    expect(state.turnQueue.length).toBe(1);
    // Cleared the moment the stage fired — a later, unrelated command can't
    // match against a stale name.
    expect(state.lastLocalCommandName).toBeNull();

    // Drive the idle-fire the way claude-tmux-queue.test.ts does: force the
    // staged pending past END_TURN_IDLE_FIRE_MS and let `flush` notice there's
    // no new JSONL data.
    state.pendingEndTurn!.stagedAt = Date.now() - 1000;
    await flush(state);

    await expect(done).resolves.toBe(0);
    expect(state.turnQueue.length).toBe(0);
    // No "turn complete" banner for a local-command settle — nothing to
    // divide from; the user just watched the command's own output print.
    expect(rec.out.some((c) => c.stream === "status" && c.data === "turn complete")).toBe(false);
  } finally {
    __forTest.uninstallSession(taskId);
  }
});

test("F1 safety valve: slot's own prompt was '/implement' (slashCommand set) — a FOREIGN '/effort' command-name + its stdout must NOT settle the turn", () => {
  const { taskId, state } = freshSession();
  try {
    const rec = recorder();
    // The task's own prompt began with a slash too (e.g. `/implement …`), so
    // `slot.slashCommand` is truthy — but it names a DIFFERENT command than
    // the one whose command-name/stdout lines are about to arrive mid-turn
    // (mirrors a dropdown-mirrored `sendSlashCommand` or a folded
    // `pasteFollowUp`, neither of which own this slot).
    state.turnQueue.push({ onChunk: rec.onChunk, resolve: () => {}, reject: () => {}, slashCommand: "/implement" });

    dispatchLine(state, commandNameLine); // <command-name>/effort</command-name>
    expect(state.lastLocalCommandName).toBe("/effort");

    dispatchLine(state, stdoutLine); // <local-command-stdout>...
    // Names differ ("/implement" !== "/effort") — must NOT stage, and the
    // /implement turn's slot must still be sitting there waiting for its
    // OWN real end_turn.
    expect(state.pendingEndTurn).toBeNull();
    expect(state.turnQueue.length).toBe(1);
  } finally {
    __forTest.uninstallSession(taskId);
  }
});

test("a stdout line with NO preceding command-name line this session → no pending stage", () => {
  const { taskId, state } = freshSession();
  try {
    const rec = recorder();
    state.turnQueue.push({ onChunk: rec.onChunk, resolve: () => {}, reject: () => {}, slashCommand: "/effort" });
    expect(state.lastLocalCommandName).toBeNull();

    // No command-name line ever seen this session — the stdout line arrives
    // "cold".
    dispatchLine(state, stdoutLine);

    expect(state.pendingEndTurn).toBeNull();
    expect(state.turnQueue.length).toBe(1);
  } finally {
    __forTest.uninstallSession(taskId);
  }
});

test("non-slash slot: the same 3-line sequence renders normally but never stages a pending end_turn", () => {
  const { taskId, state } = freshSession();
  try {
    const rec = recorder();
    __forTest.pushTurnSlot(state, rec.onChunk); // slashCommand: null

    dispatchLine(state, caveatLine);
    dispatchLine(state, commandNameLine);
    dispatchLine(state, stdoutLine);

    // Rendering is unconditional (the mapper doesn't know about the slot's
    // slashCommand) — only the SETTLE is gated on it.
    expect(rec.out.some((c) => c.stream === "user" && c.data.includes("<command-name>/effort</command-name>"))).toBe(true);
    expect(rec.out.some((c) => c.stream === "user" && c.data.includes("<local-command-stdout>Set effort level to high"))).toBe(true);

    expect(state.pendingEndTurn).toBeNull();
    expect(state.turnQueue.length).toBe(1);
  } finally {
    __forTest.uninstallSession(taskId);
  }
});

test("stdout followed by a plain assistant line (not a tool_result): the staged pending fires on that next line", async () => {
  const { taskId, state } = freshSession();
  try {
    const rec = recorder();
    const done = new Promise<number>((resolve, reject) => {
      state.turnQueue.push({ onChunk: rec.onChunk, resolve, reject, slashCommand: "/effort" });
    });

    dispatchLine(state, caveatLine);
    dispatchLine(state, commandNameLine);
    dispatchLine(state, stdoutLine);
    expect(state.pendingEndTurn).not.toBeNull();

    // A same-message continuation check never applies here (staged
    // messageId is null for a local-command settle — see
    // isEndTurnContinuation), so ANY next line fires the pending, including
    // a plain (non end_turn, non tool_result) assistant line.
    const assistantLine = JSON.stringify({
      type: "assistant",
      message: { id: "msg-later", content: [{ type: "text", text: "some later reply" }], stop_reason: "tool_use" },
    });
    dispatchLine(state, assistantLine);

    await expect(done).resolves.toBe(0);
    expect(state.turnQueue.length).toBe(0);
    // The assistant text still reaches the recorder — routed via
    // state.lastChunk (popEndOfTurn's hand-off), since the slot is gone by
    // the time this line's own content is mapped.
    expect(rec.out.some((c) => c.stream === "assistant" && c.data === "some later reply")).toBe(true);
    expect(rec.out.some((c) => c.stream === "status" && c.data === "turn complete")).toBe(false);
  } finally {
    __forTest.uninstallSession(taskId);
  }
});

test("fresh-session system/local_command shape: two system lines settle the slot the same way as the user-wrapped shape", async () => {
  const { taskId, state } = freshSession();
  try {
    const rec = recorder();
    const done = new Promise<number>((resolve, reject) => {
      state.turnQueue.push({ onChunk: rec.onChunk, resolve, reject, slashCommand: "/model" });
    });

    dispatchLine(state, freshSessionCommandNameLine);
    dispatchLine(state, freshSessionStdoutLine);

    const userChunks = rec.out.filter((c) => c.stream === "user");
    expect(userChunks.length).toBe(2);
    expect(userChunks[0]!.data).toContain("<command-name>/model</command-name>");
    expect(userChunks[1]!.data).toContain("<local-command-stdout>Kept model as Opus 4.8");

    expect(state.pendingEndTurn).not.toBeNull();
    expect(state.pendingEndTurn!.emitBanner).toBe(false);

    state.pendingEndTurn!.stagedAt = Date.now() - 1000;
    await flush(state);

    await expect(done).resolves.toBe(0);
    expect(state.turnQueue.length).toBe(0);
  } finally {
    __forTest.uninstallSession(taskId);
  }
});

/* ────────────────────────────────────────────────────────────────────────── *
 * signalIdleSettle — the idle-settle net's settlement mechanics
 * ────────────────────────────────────────────────────────────────────────── */

test("signalIdleSettle: pops the slot, emits IDLE_SETTLE_STATUS_TEXT then 'turn complete' (in that order), and clears all staging fields", async () => {
  const { taskId, state } = freshSession();
  try {
    const rec = recorder();
    const done = new Promise<number>((resolve, reject) => {
      state.turnQueue.push({ onChunk: rec.onChunk, resolve, reject, slashCommand: null });
    });
    state.pendingEndTurn = { messageId: null, uuid: undefined, emitBanner: true, stagedAt: Date.now() };
    state.holdUntilIdle = true;
    state.pendingSlashToken = "/x";
    // Set to a non-null value so popEndOfTurn (called by signalIdleSettle)
    // clearing it is actually observable, not vacuously true.
    state.lastLocalCommandName = "/effort";

    signalIdleSettle(state);

    // F6: an idle-settle must be explained in the transcript, not read as an
    // indistinguishable real end_turn — the explanatory text lands FIRST,
    // immediately before the "turn complete" banner.
    const statusTexts = rec.out.filter((c) => c.stream === "status").map((c) => c.data);
    expect(statusTexts).toEqual([IDLE_SETTLE_STATUS_TEXT, "turn complete"]);

    await expect(done).resolves.toBe(0);
    expect(state.turnQueue.length).toBe(0);
    expect(state.pendingEndTurn).toBeNull();
    expect(state.holdUntilIdle).toBe(false);
    expect(state.pendingSlashToken).toBeNull();
    // F1: popEndOfTurn (invoked at the end of signalIdleSettle) clears the
    // local-command identity gate too, alongside the other staging fields.
    expect(state.lastLocalCommandName).toBeNull();
  } finally {
    __forTest.uninstallSession(taskId);
  }
});

test("IDLE_SETTLE_STATUS_TEXT does not start with any other status-prefix sentinel (unknown-command / session-died / api-error)", () => {
  expect(IDLE_SETTLE_STATUS_TEXT.startsWith(CLAUDE_UNKNOWN_COMMAND_STATUS_PREFIX)).toBe(false);
  expect(IDLE_SETTLE_STATUS_TEXT.startsWith(SESSION_DIED_STATUS_PREFIX)).toBe(false);
  expect(IDLE_SETTLE_STATUS_TEXT.startsWith(CLAUDE_API_ERROR_STATUS_PREFIX)).toBe(false);
});

/* ────────────────────────────────────────────────────────────────────────── *
 * dismissTmuxPrompt — horizontal nav (nav: "horizontal")
 * ────────────────────────────────────────────────────────────────────────── */

// choices keyed "1".."6" in literal pane order (index i => key String(i+1)) —
// the same order matchSliderModal/matchNumberedModal always produce.
const sixChoices = ["1", "2", "3", "4", "5", "6"].map((key) => ({ key, label: `choice ${key}` }));

test("dismissTmuxPrompt: nav:'horizontal' + positive delta sends Right,Right,Enter (in order, ignoring -t <session> args)", async () => {
  await withRecordingTmuxBin(async (logPath) => {
    const { taskId } = freshSession();
    try {
      // cursorIndex 2 (currently on key "3") → target key "5" is index 4 →
      // delta +2 → two Right presses before the confirming Enter.
      const ok = await dismissTmuxPrompt(taskId, "5", { choices: sixChoices, cursorIndex: 2, nav: "horizontal" });
      expect(ok).toBe(true);
      const keys = readTmuxLog(logPath)
        .filter((e) => e.argv[0] === "send-keys")
        .map((e) => e.argv[e.argv.length - 1]);
      expect(keys).toEqual(["Right", "Right", "Enter"]);
    } finally {
      __forTest.uninstallSession(taskId);
    }
  });
});

test("dismissTmuxPrompt: nav:'horizontal' + negative delta sends Left,Left,Enter", async () => {
  await withRecordingTmuxBin(async (logPath) => {
    const { taskId } = freshSession();
    try {
      // Same cursorIndex 2 → target key "1" is index 0 → delta -2 → two Left
      // presses before the confirming Enter.
      const ok = await dismissTmuxPrompt(taskId, "1", { choices: sixChoices, cursorIndex: 2, nav: "horizontal" });
      expect(ok).toBe(true);
      const keys = readTmuxLog(logPath)
        .filter((e) => e.argv[0] === "send-keys")
        .map((e) => e.argv[e.argv.length - 1]);
      expect(keys).toEqual(["Left", "Left", "Enter"]);
    } finally {
      __forTest.uninstallSession(taskId);
    }
  });
});

test("dismissTmuxPrompt: no nav (regression guard) still sends Down,Down,Enter for a vertical numbered modal", async () => {
  await withRecordingTmuxBin(async (logPath) => {
    const { taskId } = freshSession();
    try {
      // cursorIndex 0 → target key "3" is index 2 → delta +2 → two Down
      // presses before the confirming Enter. No `nav` passed at all.
      const ok = await dismissTmuxPrompt(taskId, "3", { choices: sixChoices, cursorIndex: 0 });
      expect(ok).toBe(true);
      const keys = readTmuxLog(logPath)
        .filter((e) => e.argv[0] === "send-keys")
        .map((e) => e.argv[e.argv.length - 1]);
      expect(keys).toEqual(["Down", "Down", "Enter"]);
    } finally {
      __forTest.uninstallSession(taskId);
    }
  });
});

/* ────────────────────────────────────────────────────────────────────────── *
 * sendSlashCommand({ autoConfirm }) — the dropdown-mirror auto-accept step
 * ────────────────────────────────────────────────────────────────────────── */

// Verbatim shape from the plan (§2 / §3.5): claude's mid-conversation
// "Change effort level?" confirm, cursor on option 1 ("Yes, switch to …").
const effortConfirmPane = [
  "Change effort level?",
  "Your next response will be slower and use more tokens",
  "",
  "This conversation is cached for the current effort level. Switching to low means the full history gets re-read on your next message.",
  "",
  "\u276F 1. Yes, switch to low",
  "  2. No, go back",
].join("\n");

// Same shape, but the OTHER kind's header — must never auto-accept a
// "Switch model?" confirm when the mirror call was for effort.
const switchModelConfirmPane = [
  "Switch model?",
  "Your next response will be slower and use more tokens",
  "",
  "This conversation is cached for the current model. Switching to Opus 5 means the full history gets re-read on your next message.",
  "",
  "\u276F 1. Yes, switch to Opus 5",
  "  2. No, go back",
].join("\n");

// Idle input box — no modal at all (matchNumberedModal finds no numbered
// lines, so matchSlashConfirmModal short-circuits to null regardless of kind).
const idlePane = [
  "\u2500".repeat(80),
  "\u276F ",
  "\u2500".repeat(80),
  "\u23F5\u23F5 bypass permissions on (shift+tab to cycle) \u00B7 \u2190 1 agent",
].join("\n");

test("sendSlashCommand({autoConfirm}): a matching confirm pane sends the auto-accept Enter", async () => {
  await withRecordingTmuxBin(async (logPath) => {
    const prevSettle = __forTest.setSlashCommandSettleMs(0);
    const { taskId } = freshSession();
    let captureCalls = 0;
    const prevCapture = __forTest.setCaptureConfirmPane(() => {
      captureCalls++;
      return effortConfirmPane;
    });
    try {
      const ok = sendSlashCommand(taskId, "/effort low", { autoConfirm: "effort" });
      expect(ok).toBe(true);

      await __forTest.pasteChains.get(taskId);

      expect(captureCalls).toBeGreaterThan(0);
      const enters = readTmuxLog(logPath).filter(
        (e) => e.argv[0] === "send-keys" && e.argv[e.argv.length - 1] === "Enter",
      );
      // One Enter submits the "/effort low" paste itself; the second is the
      // auto-accept step's confirm.
      expect(enters.length).toBe(2);
    } finally {
      __forTest.setCaptureConfirmPane(prevCapture);
      __forTest.setSlashCommandSettleMs(prevSettle);
      __forTest.uninstallSession(taskId);
    }
  });
});

test("sendSlashCommand({autoConfirm: 'effort'}): a 'Switch model?' confirm (wrong kind) is never auto-accepted", async () => {
  await withRecordingTmuxBin(async (logPath) => {
    const prevSettle = __forTest.setSlashCommandSettleMs(0);
    const { taskId } = freshSession();
    let captureCalls = 0;
    const prevCapture = __forTest.setCaptureConfirmPane(() => {
      captureCalls++;
      return switchModelConfirmPane;
    });
    try {
      const ok = sendSlashCommand(taskId, "/effort low", { autoConfirm: "effort" });
      expect(ok).toBe(true);

      // Let the paste settle and at least one confirm-poll attempt run
      // against the (permanently mismatched) synthetic pane, then tear the
      // session down so the poll loop's next `stillCurrent()` check bails
      // instead of spinning out the full SLASH_CONFIRM_WINDOW_MS.
      await new Promise((r) => setTimeout(r, 50));
      expect(captureCalls).toBeGreaterThan(0);
      __forTest.uninstallSession(taskId);
      await __forTest.pasteChains.get(taskId);

      const enters = readTmuxLog(logPath).filter(
        (e) => e.argv[0] === "send-keys" && e.argv[e.argv.length - 1] === "Enter",
      );
      // Only the paste's own submit Enter — no confirm Enter.
      expect(enters.length).toBe(1);
    } finally {
      __forTest.setCaptureConfirmPane(prevCapture);
      __forTest.setSlashCommandSettleMs(prevSettle);
    }
  });
});

test("sendSlashCommand({autoConfirm}): an idle pane (no modal at all) is never auto-accepted", async () => {
  await withRecordingTmuxBin(async (logPath) => {
    const prevSettle = __forTest.setSlashCommandSettleMs(0);
    const { taskId } = freshSession();
    let captureCalls = 0;
    const prevCapture = __forTest.setCaptureConfirmPane(() => {
      captureCalls++;
      return idlePane;
    });
    try {
      const ok = sendSlashCommand(taskId, "/effort low", { autoConfirm: "effort" });
      expect(ok).toBe(true);

      await new Promise((r) => setTimeout(r, 50));
      expect(captureCalls).toBeGreaterThan(0);
      __forTest.uninstallSession(taskId);
      await __forTest.pasteChains.get(taskId);

      const enters = readTmuxLog(logPath).filter(
        (e) => e.argv[0] === "send-keys" && e.argv[e.argv.length - 1] === "Enter",
      );
      expect(enters.length).toBe(1);
    } finally {
      __forTest.setCaptureConfirmPane(prevCapture);
      __forTest.setSlashCommandSettleMs(prevSettle);
    }
  });
});

test("sendSlashCommand({autoConfirm}): two consecutive idle-input-box polls break the loop early — no Enter sent, and the op finishes well before the full SLASH_CONFIRM_WINDOW_MS", async () => {
  await withRecordingTmuxBin(async (logPath) => {
    const prevSettle = __forTest.setSlashCommandSettleMs(0);
    const { taskId } = freshSession();
    let captureCalls = 0;
    const prevCapture = __forTest.setCaptureConfirmPane(() => {
      captureCalls++;
      return idlePane;
    });
    try {
      const start = Date.now();
      const ok = sendSlashCommand(taskId, "/effort low", { autoConfirm: "effort" });
      expect(ok).toBe(true);

      // Let the op run to completion on its own — no manual uninstall this
      // time — to prove the EARLY EXIT itself is what ends the poll, not a
      // teardown race.
      await __forTest.pasteChains.get(taskId);
      const elapsed = Date.now() - start;

      // Two idle sightings and done: at most a couple more captures for
      // scheduling slack, nowhere near the ~10 captures a full
      // SLASH_CONFIRM_WINDOW_MS/SLASH_CONFIRM_POLL_MS window would need.
      expect(captureCalls).toBeLessThanOrEqual(3);
      // Comfortably under the full window (2s), and under 2 * SLASH_CONFIRM_POLL_MS
      // plus slack — this is the point of the early exit.
      expect(elapsed).toBeLessThan(1_000);
      expect(elapsed).toBeLessThan(SLASH_CONFIRM_POLL_MS * 5);

      const enters = readTmuxLog(logPath).filter(
        (e) => e.argv[0] === "send-keys" && e.argv[e.argv.length - 1] === "Enter",
      );
      // Only the paste's own submit Enter — never a confirm Enter on the
      // idle (no-confirm) path.
      expect(enters.length).toBe(1);
    } finally {
      __forTest.setCaptureConfirmPane(prevCapture);
      __forTest.setSlashCommandSettleMs(prevSettle);
      __forTest.uninstallSession(taskId);
    }
  });
});

test("sendSlashCommand without opts: no auto-confirm step runs at all (no Enter beyond the paste, no pane capture)", async () => {
  await withRecordingTmuxBin(async (logPath) => {
    const prevSettle = __forTest.setSlashCommandSettleMs(0);
    const { taskId } = freshSession();
    let captureCalls = 0;
    const prevCapture = __forTest.setCaptureConfirmPane(() => {
      captureCalls++;
      return effortConfirmPane; // would match if the poll ever ran
    });
    try {
      const ok = sendSlashCommand(taskId, "/effort low");
      expect(ok).toBe(true);

      await __forTest.pasteChains.get(taskId);

      expect(captureCalls).toBe(0);
      const enters = readTmuxLog(logPath).filter(
        (e) => e.argv[0] === "send-keys" && e.argv[e.argv.length - 1] === "Enter",
      );
      expect(enters.length).toBe(1);
    } finally {
      __forTest.setCaptureConfirmPane(prevCapture);
      __forTest.setSlashCommandSettleMs(prevSettle);
      __forTest.uninstallSession(taskId);
    }
  });
});
